services:
  mongo:
    image: mongo:7
    container_name: wb-mongo-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: word-battle-test
    ports:
      - '27018:27017'
    tmpfs:
      - /data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
